[tools]
java = "openjdk-21"
maven = "3"
python = "3.14"
terraform = "1"
terragrunt = "latest"
uv = "latest"
devspace = "latest"
jq = "latest"
yq = "latest"
ruby = "3.4.5"

[settings]
idiomatic_version_file_enable_tools = []
experimental = true

[settings.python]
uv_venv_auto = true
